# -*- coding: utf-8 -*-
"""Analisis sentimen amazon.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Q3ucvrWKGLthkKCcN2BX33J7yfgprpA9
"""

import pandas as pd
import matplotlib.pyplot as plt
from textblob import TextBlob
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.naive_bayes import MultinomialNB
from sklearn.feature_extraction.text import CountVectorizer

# Membaca dataset dari file excel
df = pd.read_excel('aftercleansingamazon.xlsx')

# Menambahkan kolom baru untuk sentimen
df['sentiment'] = ''

# Melakukan analisis sentimen menggunakan TextBlob
for index, row in df.iterrows():
    analysis = TextBlob(str(row['review_content']))
    # Menetapkan label sentimen berdasarkan nilai polaritas
    if analysis.sentiment.polarity > 0:
        df.at[index, 'sentiment'] = 'positive'
    elif analysis.sentiment.polarity == 0:
        df.at[index, 'sentiment'] = 'neutral'
    else:
        df.at[index, 'sentiment'] = 'negative'

# Memisahkan dataset menjadi data latih dan data uji
X_train, X_test, y_train, y_test = train_test_split(df['review_content'], df['sentiment'], test_size=0.2, random_state=42)

# Membuat model klasifikasi Naive Bayes
vectorizer = CountVectorizer()
X_train_vectorized = vectorizer.fit_transform(X_train)
model = MultinomialNB()
model.fit(X_train_vectorized, y_train)

# Menguji model dengan data uji
X_test_vectorized = vectorizer.transform(X_test)
y_pred = model.predict(X_test_vectorized)

# Menghitung akurasi model
accuracy = accuracy_score(y_test, y_pred)
print('Akurasi Model: {:.2f}%'.format(accuracy * 100))

# Menghitung jumlah ulasan untuk setiap sentimen
sentiment_counts = df['sentiment'].value_counts()

# Membuat grafik batang
plt.bar(sentiment_counts.index, sentiment_counts.values, color=['green', 'gray', 'red'])
plt.xlabel('Sentiment')
plt.ylabel('Number of Reviews')
plt.title('Sentiment Analysis on Amazon Reviews')
plt.show()

# Menyimpan hasil analisis sentimen ke file excel
df.to_excel('hasil_analisis_sentimen_amazon.xlsx', index=False)